USE picatlas;

CREATE TABLE IF NOT EXISTS DESTINATION (
  DESTINATION_ID INT AUTO_INCREMENT,
	NAME CHAR(255),
	IMG_PATH CHAR(255),
	ADDRESS CHAR(255),
  HOTEL_PRICES CHAR(255),
  TEMPERATURE_LOW CHAR(255),
  TEMPERATURE_HIGH CHAR(255),
  DESCRIPTION TEXT,
	PRIMARY KEY (DESTINATION_ID)
);

CREATE TABLE IF NOT EXISTS TAG (
	TAG_ID INT AUTO_INCREMENT,
	TAG_NAME CHAR(255),
	PRIMARY KEY (TAG_ID)
);

CREATE TABLE IF NOT EXISTS DESTINATION_TAG (
  DESTINATION_TAG_ID INT AUTO_INCREMENT,
	DESTINATION_ID INT,
	TAG_ID INT,
	FOREIGN KEY fk_destination(DESTINATION_ID) REFERENCES DESTINATION(DESTINATION_ID),
	FOREIGN KEY fk_tag(TAG_ID) REFERENCES TAG(TAG_ID),
	PRIMARY KEY (DESTINATION_TAG_ID)
);
