CREATE TABLE IF NOT EXISTS DESTINATION (
  DESTINATION_ID INT AUTO_INCREMENT,
	NAME CHAR(255),
	IMG_PATH CHAR(255),
	ADDRESS CHAR(255),
	PRIMARY KEY (DESTINATION_ID)
);

CREATE TABLE IF NOT EXISTS TAG (
	TAG_ID INT AUTO_INCREMENT,
	TAG_NAME CHAR(255)
	PRIMARY KEY (TAG_ID)
);

CREATE TABLE IF NOT EXISTS DESTINATION_TAG (
  DESTINATION_TAG_ID INT AUTO_INCREMENT,
	DESTINATION_ID INT FOREIGN_KEY,
	TAG_ID INT FOREIGN_KEY,
	PRIMARY KEY (DESTINATION_TAG_ID)
);

INSERT INTO Destinations VALUES ('Alaska', 'alaska.jpg', 'Alaska, USA');

INSERT INTO Tags VALUES (0, 'Urban');
INSERT INTO Tags VALUES (1, 'Rural');
INSERT INTO Tags VALUES (2, 'Vista');
INSERT INTO Tags VALUES (3, 'Landmark');
INSERT INTO Tags VALUES (4, 'Desert');
INSERT INTO Tags VALUES (5, 'Glacial');
INSERT INTO Tags VALUES (6, 'Flower/Field');
INSERT INTO Tags VALUES (7, 'Snow');
INSERT INTO Tags VALUES (8, 'Mountainous');
INSERT INTO Tags VALUES (9, 'Architecture');
INSERT INTO Tags VALUES (10, 'Tropical');
INSERT INTO Tags VALUES (11, '');
INSERT INTO Tags VALUES (12, '');
INSERT INTO Tags VALUES (13, '');
INSERT INTO Tags VALUES (14, '');
INSERT INTO Tags VALUES (15, '');
INSERT INTO Tags VALUES (16, '');
INSERT INTO Tags VALUES (17, '');
INSERT INTO Tags VALUES (18, '');
INSERT INTO Tags VALUES (19, '');
INSERT INTO Tags VALUES (20, '');
INSERT INTO Tags VALUES (21, '');