INSERT INTO TAG (TAG_NAME) VALUES ('Urban');
INSERT INTO TAG (TAG_NAME) VALUES ('Rural');
INSERT INTO TAG (TAG_NAME) VALUES ('Nature');
INSERT INTO TAG (TAG_NAME) VALUES ('Small-town');
INSERT INTO TAG (TAG_NAME) VALUES ('Glacier');
INSERT INTO TAG (TAG_NAME) VALUES ('Flower');
INSERT INTO TAG (TAG_NAME) VALUES ('Snow');
INSERT INTO TAG (TAG_NAME) VALUES ('Mountain');
INSERT INTO TAG (TAG_NAME) VALUES ('Landmark');
INSERT INTO TAG (TAG_NAME) VALUES ('Architecture');
INSERT INTO TAG (TAG_NAME) VALUES ('Alleys');
INSERT INTO TAG (TAG_NAME) VALUES ('Night');
INSERT INTO TAG (TAG_NAME) VALUES ('Maritime');
INSERT INTO TAG (TAG_NAME) VALUES ('Vista');
INSERT INTO TAG (TAG_NAME) VALUES ('Tropical');
INSERT INTO TAG (TAG_NAME) VALUES ('Desert');

INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Alaska', './img/destinations/alaska.jpg', 'Alaska, USA', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Known for its diverse terrain of open spaces, mountains and forests, with abundant wildlife and many small towns.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Bandarban', './img/destinations/bandarban.jpg', 'Bandarban District, Bangladesh', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Bern', './img/destinations/bern.jpg', 'Bern, Switzerland', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Boston Old Street', './img/destinations/boston-old-street.jpg', 'Boston, MA, USA', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Central Park', './img/destinations/central-park-fall.jpg', 'New York, NY, USA', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Chicago', './img/destinations/chicago.jpg', 'Chicago, IL, USA', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Deoksugung Palace', './img/destinations/deoksugung.jpg', 'Seoul, South Korea', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Faroe Islands', './img/destinations/faroe.jpg', 'Faroe Islands', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Ginza', './img/destinations/ginza.jpg', 'Ginza, Chuo, Tokyo', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Great Smoky Mountains', './img/destinations/great-smoky-mountains.jpg', 'Tennessee-North Carolina', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Hollow Rock', './img/destinations/hollow-rock.jpg', 'Grand Portage, MN 55605, USA', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Hong Kong', './img/destinations/hong-kong.jpg', 'Hong Kong, China', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Mt St Helens', './img/destinations/mt-st-helens.jpg', 'Mt St Helens, WA, USA', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Pachuca', './img/destinations/pachuca.jpg', 'Pachuca, Hidalgo, Mexico', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Rainy Tokyo Alley', './img/destinations/rainy-tokyo-alley.jpg', 'Tokyo, Japan', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('San Francisco', './img/destinations/san-francisco.jpg', 'San Francisco, CA, USA', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Strokkur Geyser', './img/destinations/strokkur-geyser.jpg', 'Haukadalur, Iceland', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Tulips in Netherlands', './img/destinations/netherlands.jpg', 'Netherlands', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Wasatch Range', './img/destinations/wasatch-range.jpg', '1281 Warm Springs Rd, Midway, UT 84049, USA', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Zion National Park', './img/destinations/zion.jpg', 'Zion National Park, UT, USA', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Vancouver', './img/destinations/vancouver.jpg', 'Vancouver, BC, Canada', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('North Vancouver', './img/destinations/north-vancouver.jpg', 'North Vancouver, BC, Canada', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Dublin', './img/destinations/dublin.jpg', 'Dublin, Ireland', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Machu Picchu', './img/destinations/machu-picchu.jpg', 'Machu Picchu, Peru', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Dubai', './img/destinations/dubai.jpg', 'Dubai, UAE', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Bora Bora', './img/destinations/bora-bora.jpg', 'Bora Bora, French Polynesia', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Berlin', './img/destinations/berlin.jpg', 'Berlin, Germany', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Lapland', './img/destinations/lapland.jpg', 'Lapland, Finland', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('London', './img/destinations/london.jpg', 'London, UK', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Vietnam', './img/destinations/vietnam.jpg', 'Vietnam', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Moscow', './img/destinations/moscow.jpg', 'Moscow, Russia', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');
INSERT INTO DESTINATION (NAME, IMG_PATH, ADDRESS, HOTEL_PRICES, TEMPERATURE_LOW, TEMPERATURE_HIGH, DESCRIPTION) VALUES ('Mongolia', './img/destinations/mongolia.jpg', 'Mongolia', '3-star hotel averaging $149, 5-star averaging $115', '-26C', '22C', 'Great destination for all.');

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(1, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(1, 14);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(1, 7);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(1, 5);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(2, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(2, 6);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(2, 14);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(2, 8);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(3, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(3, 4);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(3, 10);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(4, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(4, 12);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(4, 10);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(5, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(5, 12);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(5, 10);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(6, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(6, 12);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(6, 8);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(7, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(7, 10);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(8, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(8, 9);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(8, 13);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(8, 14);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(9, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(9, 12);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(9, 10);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(10, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(10, 8);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(10, 14);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(11, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(11, 13);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(11, 7);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(11, 5);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(12, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(12, 12);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(12, 10);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(13, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(13, 8);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(13, 9);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(14, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(14, 2);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(14, 10);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(15, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(15, 12);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(16, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(16, 14);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(16, 9);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(17, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(17, 9);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(17, 14);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(18, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(18, 6);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(18, 14);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(19, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(19, 8);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(19, 14);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(20, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(20, 14);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(20, 8);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(20, 6);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(21, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(21, 10);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(22, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(22, 8);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(23, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(23, 10);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(23, 11);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(23, 12);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(24, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(24, 8);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(25, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(25, 10);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(25, 13);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(26, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(26, 13);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(26, 14);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(26, 15);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(27, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(27, 10);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(27, 12);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(28, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(28, 7);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(28, 9);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(28, 14);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(29, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(29, 10);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(29, 11);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(29, 12);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(30, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(30, 13);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(30, 14);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(30, 15);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(31, 1);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(31, 10);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(31, 12);

INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(32, 3);
INSERT INTO DESTINATION_TAG (DESTINATION_ID, TAG_ID) VALUES(32, 14);
